# Generated by Django 4.2.3 on 2023-09-26 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=200)),
                ('mac_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LaundryMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('machine_type', models.CharField(choices=[('W', 'Washer'), ('D', 'Dryer')], default='W', max_length=2)),
                ('status', models.CharField(choices=[('A', 'Available'), ('R', 'Running'), ('F', 'Finished')], default='A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='KasaPowerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.DecimalField(decimal_places=3, max_digits=10)),
                ('voltage', models.DecimalField(decimal_places=3, max_digits=10)),
                ('power', models.DecimalField(decimal_places=3, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('kasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='old.kasa')),
            ],
        ),
        migrations.AddField(
            model_name='kasa',
            name='power_integration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='old.laundrymachine'),
        ),
    ]
