# Generated by Django 4.2.3 on 2023-10-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0002_laundrymachine_avg_run_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundrymachine',
            name='last_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laundrymachine',
            name='last_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
