# Generated by Django 4.2.3 on 2023-10-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0003_alter_laundrymachine_last_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrymachine',
            name='last_status_change_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
