# Generated by Django 4.2.3 on 2023-10-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0004_laundrymachine_last_status_change_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.CharField(max_length=200)),
                ('discord_name', models.CharField(max_length=200)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='old.laundrymachine')),
            ],
        ),
    ]
