# Generated by Django 4.2.3 on 2023-10-13 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0006_remove_discordhook_machine_discordhook_machines'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordhook',
            name='webhook_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
