# Generated by Django 4.2.3 on 2023-10-13 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0007_discordhook_webhook_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordhook',
            name='ping_tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
