# Generated by Django 4.2.3 on 2023-11-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old', '0010_alter_laundrymachine_last_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrymachine',
            name='eta',
            field=models.IntegerField(default=0),
        ),
    ]
